name: 'Bump Version'

on:
  push:
    branches:
      - 'feature/elineb/CVD19-1149-add-cd'

jobs:
  bump-version:
    name: 'Bump package version'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        r-version: ['4.1.1']

    steps:
      - name: 'Checkout source code'
        uses: 'actions/checkout@v2'
        with:
          ref: ${{ github.ref }}
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@f57f1301a053485946083d7a45022b278929a78a
        with:
          r-version: ${{ matrix.r-version }}
      - name: Install ubuntu dependecie
        run: |
          sudo apt install libcurl4-openssl-dev
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "usethis"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      - name: 'cat DESCRIPTION'
        run: cat ./DESCRIPTION
      - name: Version bump
        run: usethis::use_version('minor')
        shell: Rscript {0}
      - name: 'cat DESCRIPTION'
        run: cat ./DESCRIPTION
      - name: Commit tags
        uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        with:
          # The arguments for the `git add` command (see the paragraph below for more info)
          # Default: '.'
          add: '.'
    
          # Determines the way the action fills missing author name and email. Three options are available:
          # - github_actor -> UserName <UserName@users.noreply.github.com>
          # - user_info -> Your Display Name <your-actual@email.com>
          # - github_actions -> github-actions <email associated with the github logo>
          # Default: github_actor
          default_author: github_actions
      
          # The message for the commit.
          # Default: 'Commit from GitHub Actions (name of the workflow)'
          message: 'Package version bump'
      
          # The way the action should handle pathspec errors from the add and remove commands. Three options are available:
          # - ignore -> errors will be logged but the step won't fail
          # - exitImmediately -> the action will stop right away, and the step will fail
          # - exitAtEnd -> the action will go on, every pathspec error will be logged at the end, the step will fail.
          # Default: ignore
          pathspec_error_handling: ignore
      
          # Whether to push the commit and, if any, its tags to the repo. It can also be used to set the git push arguments (see the paragraph below for more info)
          # Default: true
          push: true